# Generated by Django 4.0.4 on 2022-06-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_rank_alter_boost_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='image',
            field=models.ImageField(upload_to='Frontend/static/dmc_ranks'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='music',
            field=models.FileField(upload_to='Frontend/static/music'),
        ),
    ]
